---
title: Conclusion
output-file: index
header-includes:
  - \setcounter{page}{6}  
---
The work done on OpenIVIS this summer was overall successful. The new physical designs for varying imaging methods has allowed the system to become more modular in its capabilities. The system was able to successfully capture the fluorescence intensities of multiple concentrations of FITC diluted in ethanol. When changing exposure times, 0.1 seconds best demonstrated the positive trend between FITC concentration and pixel intensity. The system was also able to capture laser speckle images and run variations of data processing code on them. However, further work is necessary to fully expand those capabilities in both image capture and data processing. Additionally, the system was verified for other capabilities such as time lapse imaging and anthocyanin response imaging. 

Future work on this project should be focused on fine tuning the LSCI pipeline. Altering the physical setup and code for image capture will help make higher resolution laser speckle contrast images. Additionally, the image processing system can be worked on for better LSCI analysis. Finally, further documentation on this work will help make the results of this project more accessible and develop its open source capabilities.
